apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: java-demo-namespace
spec:
  type: LoadBalancer
  selector:
    app: java-app
  ports:
    - port: 80
      targetPort: 8080
